<header>
    <h1>Tout sur la League</h1>
    <p>Les players, les teams et l'actu des matchs</p>
</header>

<main>
    <section class="a_la_une">
        <h2>La team a la une</h2>
        <div class="pres">
            <div class="team">
                <div class="players">
                    <div class="player logo-block">
                        <?php $logo = $data["featuredTeam"]->getLogo(); ?>
                        <img class="team-logo" src="<?= $logo->getUrl() ?>" alt="<?= $logo->getAlt() ?>" loading="lazy">
                    </div>

                    <?php $first = true; /* Flag to add overlay only on the first player image */ ?>
                    <?php foreach ($data["featuredTeam"]->getPlayers() as $player) : ?>
                        <?php $image = $player->getImage(); ?>
                        <div class="player">
                            <?php if ($first) : ?>
                                <div class="overlay-text">
                                    <h3>Angry Owls</h3>
                                    <p>Les Players</p>
                                </div>
                                <?php $first = false; ?>
                            <?php endif; ?>
                            <img src="<?= $image->getUrl() ?>" alt="<?= $image->getAlt() ?>" loading="lazy">
                            <h3><?= $player->getNickName() ?></h3>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </section>

    <section class="players_a_la_une">
        <h2>Les players à la une</h2>
        <div class = "cards">
            <?php foreach ($data["featuredPlayers"] as $player) { ?>
                <div class="<?= $player->getNickname() ?>">
                    <?php $image = $player->getImage(); ?>
                    <img src="<?= $image->getUrl() ?>" alt="<?= $image->getAlt() ?>" loading="lazy">
                    <h3><?= $player->getNickname() ?></h3>
                    <p><?= $player->getTeam()["name"] ?></p>
                </div>
            <?php } ?>
        </div>
    </section>

    <section class="match_a_la_une">
        <h2>Le dernier Match</h2>
        <div id="teams">
            <h2><?= $data["lastGame"]->getName() ?></h2>
            <p><?= $data["lastGame"]->getDate()->format("d/m/Y") ?></p>

            <div>
                <?php
                    $team = $data["lastGame"]->getTeam_1();
                    $logo = $team->getLogo();
                ?>
                <img src="<?= $logo->getUrl() ?>" alt="<?= $logo->getAlt() ?>" <?php if ($team->getId() === $data["lastGame"]->getWinner()) { ?> class="winner" <?php } ?> loading="lazy">

                <?php
                    $team = $data["lastGame"]->getTeam_2();
                    $logo = $team->getLogo();
                ?>
                <img src="<?= $logo->getUrl() ?>" alt="<?= $logo->getAlt() ?>" <?php if ($team->getId() === $data["lastGame"]->getWinner()) { ?> class="winner" <?php } ?> loading="lazy">
            </div>
        </div>
    </section>
</main>