<main>
    <section>
        <?php $game = $data["game"]; ?>
        <h1><?= $game->getName() ?></h1>
        <p><?= $game->getDate()->format("d/m/Y") ?></p>

        <?php
        $team1 = $game->getTeam_1();
        $logo1 = $team1->getLogo();
        $team2 = $game->getTeam_2();
        $logo2 = $team2->getLogo();
        ?>

        <div class="logos">
            <img src="<?= $logo1->getUrl() ?>" alt="<?= $logo1->getAlt() ?>" loading="lazy">
            <img src="<?= $logo2->getUrl() ?>" alt="<?= $logo2->getAlt() ?>" loading="lazy">
        </div>
        <h1 class = "perf">Les Performances</h1>
        <!-- Found table class on https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/table -->
        <table class="tableau-des-joueurs">
            <thead>
            <tr class="top">
                <th>Player</th>
                <th>Team</th>
                <th>Points</th>
                <th>Assists</th>
            </tr>
            </thead>
            <tbody>


                <?php foreach ($data["team1Players"] as $joueur) { ?>
                    <?php
                    $performances = $joueur->getStats();
                    $playerPerf = $performances[0] ?? null;
                    ?>
                    <tr class="teams">
                        <td class = "players"><?= $joueur->getNickname() ?></td>
                        <td class = "team"><?= $joueur->getTeam()["name"] ?></td>
                        <td><?= $playerPerf ? $playerPerf->getPoints() : 'N/A' /*found with ai, asked it why the performances werent appearing */?></td>
                        <td><?= $playerPerf ? $playerPerf->getAssists() : 'N/A' ?></td>
                    </tr>
                <?php } ?>

                <?php foreach ($data["team2Players"] as $joueur) { ?>
                    <?php
                    $performances = $joueur->getStats();
                    $playerPerf = $performances[0] ?? null;
                    ?>
                    <tr class="teams">
                        <td class = "players"><?= $joueur->getNickname() ?></td>
                        <td class = "team"><?= $joueur->getTeam()["name"] ?></td>
                        <td><?= $playerPerf ? $playerPerf->getPoints() : 'N/A' ?></td>
                        <td><?= $playerPerf ? $playerPerf->getAssists() : 'N/A' ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </section>
</main>
