<main>

    <section>
        <h1><?= $game->getName() ?></h1>
        <p> <?=$game->getDate()->format("d-m-Y")?></p>
        <?php
            $team1 = $game->getTeam_1();
            $logo1 = $team1->getLogo();
            $team2 = $game->getTeam_2();
            $logo2 = $team2->getLogo(); ?>

        <div class = "logos">
            <img src="<?= $logo1->getUrl() ?>" alt="<?= $logo1->getAlt() ?>">
            <img src="<?= $logo2->getUrl() ?>" alt="<?= $logo2->getAlt() ?>">
        </div>
        <div class = "tableau-des-joueurs">
            <div class = "top">
                <p>Player</p>
                <p>Team</p>
                <p>Points</p>
                <p>Assists</p>
            </div>
            <div class = "team1">
                <?php foreach ($team1->getPlayers() as $joueur) { ?>
                    <p><?= $player->getNickName() ?></p>
                    <p><?= $player->getTeam()["name"] ?></p>
                    <p><?= $playerPerf->getPoints() ?></p>
                    <p><?= $playerPerf->getAssists() ?></p>
                <?php } ?>
            </div>

            <div class = "team2">
                <?php foreach ($team2->getPlayers() as $joueur) { ?>
                    <p><?= $player->getNickName() ?></p>
                    <p><?= $player->getTeam()["name"] ?></p>
                    <p><?= $playerPerf->getPoints() ?></p>
                    <p><?= $playerPerf->getAssists() ?></p>
                <?php } ?>
            </div>
        </div>
    </section>
</main>