<main> 
    <h1> LES MATCHS </h1>
    <section> 
        <?php foreach ($data as $game) { ?>
            <div class="match"> 
                <p> <?=$game->getName() ?> </p>
                <p> <?=$game->getDate()->format("d-m-Y")?></p>
                <div>
                    <p> hgfhjfyt </p>
                </div>
                <button> detail du match </button>
            </div>
        <?php } ?>
    </section>
</main>