<main>
    <h1>LES PLAYERS DE LA LEAGUE</h1>
    <section>
        <?php foreach($data as $player) { 
            $image = $player->getImage() ?>
            <div>
                <img src="<?= $image->getUrl() ?>" alt="<?= $image->getAlt() ?>">
                <p><?= $player->getNickname() ?></p>
                <p><?= $player->getTeamName() ?></p>
                <button onclick="window.location.href = '?route=player&playerId=<?= $player->getId() ?>';">DECOUVREZ <?= $player->getNickname() ?></button>
            </div>
        <?php } ?>
    </section>
</main>