<main>
    <?php
        $player = $data["player"];
        $image = $player->getImage;
        $teamPlayers = $data["playerTeam"];

        $playerPerfs = $player->getStats();
    ?>

    <section>
        <h2><?= $player->getNickname() ?></h2>
        <img src="<?= $image->getUrl() ?>" alt="<?= $image->getAlt() ?>">
    </section>

    <section>
        <h2>SES PERFORMANCES</h2>
        <table>
            <thead>
                <th>TEAM ADVERSE</th>
                <th>POINTS</th>
                <th>ASSISTS</th>
                <th>VICTOIRE ?</th>
            </thead>
            <tbody>
                <?php foreach($playerPerfs as $playerPerf) {
                    $game = $playerPerf->getGame();
                    $teamWin = "Non";

                    if ($game->getTeam_1()->getName() === $player->getTeam()["name"]) {
                        $opponentTeam = $game->getTeam_2()->getName();

                        if ($game->getWinner() === $game->getTeam_1()->getId()) {
                            $teamWin = "Oui";
                        }
                    } else {
                        $opponentTeam = $game->getTeam_1()->getName();

                        if ($game->getWinner() === $game->getTeam_2()->getId()) {
                            $teamWin = "Oui";
                        }
                    }
                ?>
                    <td><?= $opponentTeam ?></td>
                    <td><?= $playerPerf->getPoints() ?></td>
                    <td><?= $playerPerf->getAssists() ?></td>
                    <td><?= $teamWin ?></td>
                <?php } ?>
            </tbody>
        </table>
    </section>

    <section>
        <h2>SA TEAM</h2>
        <?php foreach($teamPlayers as $teamate) {
            $image = $teamate->getImage() ?>
            <div>
                <img src="<?= $image->getUrl() ?>" alt="<?= $image->getAlt() ?>">
                <p><?= $teamate->getNickname() ?></p>
                <button onclick="window.location.href = '?route=player&playerId=<?= $teamate->getId() ?>';">DECOUVREZ <?= $teamate->getNickname() ?></button>
            </div>
        <?php } ?>
    </section>
</main>