<main>
    <h1>LES TEAMS DE LA LEAGUE</h1>
    <section>
        <?php foreach ($data as $team) {
            $media = new MediaManager;
            $logo = $media->findOne($team["logo"])?>
            <div>
                <img src="<?= $logo["url"] ?>" alt="<?= $logo["alt"] ?>">
                <p><?= $team["name"] ?></p>
                <p><?= $team["description"] ?></p>
                <button>DECOUVREZ <?= $team["name"] ?></button>
            </div>
        <?php } ?>
    </section>
</main>