<main>
    <h1>LES TEAMS DE LA LEAGUE</h1>
    <section>
        <?php foreach ($data as $team) {
            $logo = $team->getLogo(); ?>
            
            <div>
                <img src="<?= $logo->getUrl() ?>" alt="<?= $logo->getAlt() ?>">
                <p><?= $team->getName() ?></p>
                <p><?= $team->getDescription() ?></p>
                <button onclick="window.location.href = '?route=team&teamId=<?= $team->getId() ?>';">DECOUVREZ <?= $team->getName() ?></button>
            </div>
        <?php } ?>
    </section>
</main>