<main>
    <?php $team = $data[0] ?>

    <h1><?= $team->getName() ?></h1>
    <section>
        <?php foreach($team->getPlayers() as $player) {
            $image = $player->getImage() ?>
            <div>
                <img src="<?= $image->getUrl() ?>" alt="<?= $image->getAlt() ?>" loading="lazy">
                <p><?= $player->getNickname() ?></p>
                <button onclick="window.location.href = '?route=player&playerId=<?= $player->getId() ?>';">DECOUVREZ <?= $player->getNickname() ?></button>
            </div>
        <?php } ?>
    </section>
</main>